@baseUrl = http://localhost:5079

### Get all teams
GET {{baseUrl}}/Team
Accept: application/json

###

### Create team
POST {{baseUrl}}/Team
Content-Type: application/json
Accept: application/json

{
  "description": "Top-tier Valorant roster",
  "points": 120,
  "imageUrl": null,
  "managerId": 1
}

###

### Get team by id
GET {{baseUrl}}/Team/1
Accept: application/json

###

### Update existing team
PUT {{baseUrl}}/Team/1
Content-Type: application/json

{
  "description": "Updated roster info",
  "points": 150,
  "imageUrl": null,
  "managerId": 1
}

###

### Delete team
DELETE {{baseUrl}}/Team/1
Accept: application/json
