@baseUrl = http://localhost:5079

### Get all users
GET {{baseUrl}}/User
Accept: application/json

###

### Get user by id
GET {{baseUrl}}/User/1
Accept: application/json

###

### Create user
POST {{baseUrl}}/User
Content-Type: application/json
Accept: application/json

{
  "role": "Player",
  "firstName": "Harold",
  "lastName": "Ponte da Costa",
  "userName": "ItzHarold",
  "email": "harold@example.com",
  "password": "Password",
  "dob": "2003-01-01T00:00:00",
  "teamId": null,
  "imageUrl": null
}

###

### Update existing user
PUT {{baseUrl}}/User/1
Content-Type: application/json

{
  "role": "Player",
  "firstName": "HaroldUpdated",
  "lastName": "Ponte",
  "userName": "ItzHarold",
  "email": "harold@example.com",
  "password": "UpdatedValue",
  "dob": "2003-01-01T00:00:00",
  "teamId": null,
  "imageUrl": null
}

###

### Delete user
DELETE {{baseUrl}}/User/1
Accept: application/json
